#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd "${SCRIPT_DIR}" || exit
./mvnw compile exec:java -Dexec.mainClass="com.cisco.mobility.api.demo.MainKt" -Dexec.args="$*"
